name: Changeset

on:
  push:
    branches:
      - master
      - release-*-patch
jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run pre-release preparations
        run: node scripts/pre-release.js
      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          # Calls out to `changeset version`, but also runs prettier
          version: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          HUSKY: '0'
